# Generated by Django 4.2 on 2024-01-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название поста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание поста')),
                ('image', models.ImageField(upload_to='posts-images/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
